### ISSUE TITLE
[Doc] Specify the mmsegmentation version

### ISSUE THREAD

**Issue by robinloujun** [Tsinghua-MARS-Lab/Online-HD-Map-Construction-CVPR2023#4]
Propose to specify the version of mmseg as dependency of mmdetection3d. As the MMDetection3D V0.17.3 is suggested, the latest mmsegmentation does not work with it.

I am using mmsegmentation==0.14.1

```
cd mmdetection3d-0.17.3
pip install mmsegmentation==0.14.1
pip install -v -e .
```

**Comment by yuantianyuan01** [comment]
Thank you for your suggestion. However, we have already listed the recommended environments [here](https://github.com/Tsinghua-MARS-Lab/Online-HD-Map-Construction-CVPR2023/blob/master/resources/docs/get_started.md#1-environment).
